const baseRecipe={flour:6000,sugar:290,salt:136,yeast:60,water:3700,oil:360,potato:2600};
const totalBaseWeight=Object.values(baseRecipe).reduce((a,b)=>a+b,0);
const pages=document.querySelectorAll('.page-section'),navLinks=document.querySelectorAll('.nav-link'),menu=document.getElementById('mainNav'),menuBtn=document.getElementById('menuBtn');
function showSection(id){pages.forEach(p=>p.classList.toggle('active',p.id===id));navLinks.forEach(b=>b.classList.toggle('active',b.dataset.nav===id));menu.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.nav)));
menuBtn.addEventListener('click',()=>menu.classList.toggle('open'));
document.querySelectorAll('.recipe-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.recipe-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.recipe-page').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.recipePage).classList.add('active')}));
const ingredient=document.getElementById('ingredientSelect'),target=document.getElementById('targetWeight'),unit=document.getElementById('unitSelect'),msg=document.getElementById('calcMessage'),multi=document.getElementById('multiplier'),total=document.getElementById('totalWeight');
const out={flour:document.getElementById('out-flour'),sugar:document.getElementById('out-sugar'),salt:document.getElementById('out-salt'),yeast:document.getElementById('out-yeast'),water:document.getElementById('out-water'),oil:document.getElementById('out-oil'),potato:document.getElementById('out-potato')};
const w80=document.getElementById('out-water80'),w20=document.getElementById('out-water20');
function fmt(g){return unit.value==='kg'?`${(g/1000).toLocaleString(undefined,{maximumFractionDigits:3})} kg`:`${Math.round(g).toLocaleString()} g`}
function render(m=1){Object.entries(baseRecipe).forEach(([k,v])=>out[k].textContent=fmt(v*m));const w=baseRecipe.water*m;w80.textContent=fmt(w*.8);w20.textContent=fmt(w*.2);total.textContent=fmt(totalBaseWeight*m);multi.textContent=`×${m.toFixed(3)}`}
function calculate(){let v=Number(target.value);if(!Number.isFinite(v)||v<=0){msg.textContent='请输入大于 0 的目标重量。';target.focus();return}if(unit.value==='kg')v*=1000;const m=v/baseRecipe[ingredient.value];render(m);msg.textContent=`已按 ${ingredient.options[ingredient.selectedIndex].text} 作为基准完成换算。`}
document.getElementById('calculateBtn').addEventListener('click',calculate);document.getElementById('resetBtn').addEventListener('click',()=>{ingredient.value='flour';target.value='';unit.value='g';render(1);msg.textContent='请输入重量开始计算。';target.focus()});target.addEventListener('keydown',e=>{if(e.key==='Enter')calculate()});unit.addEventListener('change',()=>render(Number(multi.textContent.replace('×',''))||1));document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>{unit.value='g';target.value=b.dataset.quick;calculate()}));render(1);
